apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: algorithm-compare-ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - http:
        paths:
          - path: /**
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8081
