apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    com.docker.project: core
  name: core
  namespace: algc
spec:
  replicas: 1
  selector:
    matchLabels:
      com.docker.project: core
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        com.docker.project: core
    spec:
      containers:
        - env:
            - name: CORS_ALLOWED_ORIGINS
              value: "*"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka.algc.svc.cluster.local:8083/eureka/
            - name: LOGGING_LEVEL_COM_REDDEV_ALGORITHMCOMPARE
              value: INFO
            - name: PLUGIN_PATH
              value: /core/plugins-zipped
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: http://admin.algc.svc.cluster.local:8082
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb.algc.svc.cluster.local
            - name: SPRING_DATA_REDIS_HOST
              value: redis.algc.svc.cluster.local
          image: algorithmcompare_core:latest
          imagePullPolicy: Never
          name: core
          ports:
            - containerPort: 8084
              protocol: TCP
          resources: {}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            failureThreshold: 30
            periodSeconds: 10
      restartPolicy: Always
status: {}
