apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: algc
spec:
  ports:
    - name: 8083-tcp
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    com.docker.project: eureka
status:
  loadBalancer: {}
