apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    com.docker.project: redis
  name: redis
  namespace: algc
spec:
  replicas: 1
  selector:
    matchLabels:
      com.docker.project: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        com.docker.project: redis
    spec:
      containers:
        - image: redis:7.0.8
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
