server:
  port: 8084

spring:
  profiles:
    active: prod
  boot:
    admin:
      client:
        enabled: true
        auto-registration: true
        url: http://localhost:8082
        username: admin
        password: admin
        instance:
          metadata:
            user:
              name: admin
              password: admin
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: test
    mongodb:
      port: 27017
      host: localhost
      database: reactive-db
      min-connections-per-host: 10
      max-connections-per-host: 100
      server-selection-timeout: 10000
      max-wait-time: 10000
      connect-timeout: 10000
  quartz:
    job-store-type: memory
    properties:
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.threadPool.threadCount: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.reddev.algorithmcompare: DEBUG
    org.mongodb: INFO

cors:
  allowed:
    origins: http://localhost:4200

job:
  seconds:
    old:
      data: 21600
  trigger:
    timeout: 21600000

plugin:
  basePath: ^modified.basedir^
  path: ${plugin.basePath}/plugins-zipped

cache:
  services:
    - name: executeAlgorithm
      ttl: 240
    - name: availableAlgorithms
      ttl: 1440