server:
  port: 8084

spring:
  application:
    name: core
  profiles:
    active: prod
  boot:
    admin:
      client:
        url: http://localhost:8082
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: test
    mongodb:
      port: 27017
      host: localhost
      database: reactive-db
      min-connections-per-host: 10
      max-connections-per-host: 100
      server-selection-timeout: 10000
      max-wait-time: 10000
      connect-timeout: 10000
  quartz:
    job-store-type: memory
    properties:
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.threadPool.threadCount: 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
    register-with-eureka: true
    fetch-registry: true
    register-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.reddev.algorithmcompare: INFO
    org.mongodb: INFO

cors:
  allowed:
    origins: http://localhost:4200

job:
  seconds:
    old:
      data: 21600
  trigger:
    timeout: 21600000

plugin:
  basePath: /home/reddev/Projects/AlgorithmCompare/AlgorithmCompareBE #CHANGEME
  path: ${plugin.basePath}/plugins-zipped

cache:
  services:
    - name: executeAlgorithm
      ttl: 240
    - name: availableAlgorithms
      ttl: 1440