version: '3.8'

networks:
  algorithm-compare-network:

services:
  algorithm-compare-be:
    container_name: algorithm-compare-be
    build:
      context: ../AlgorithmCompareBE
      dockerfile: algorithm-compare-be.dockerfile
    ports:
      - '8084:8084'
    depends_on:
      - mongodb
      - redis
      - admin-monitor
      - eureka
      - gateway
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_REDIS_HOST=redis
      - PLUGIN_PATH=/algorithm-compare-be/plugins-zipped
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8083/eureka/
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://admin-monitor:8082
    networks:
      - algorithm-compare-network

  admin-monitor:
    container_name: admin-monitor
    build:
      context: ../AlgorithmCompareBE/AdminMonitor
      dockerfile: admin-monitor.dockerfile
    ports:
      - '8082:8082'
    networks:
      - algorithm-compare-network

  gateway:
    container_name: gateway
    build:
      context: ../AlgorithmCompareBE/Gateway
      dockerfile: gateway.dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - admin-monitor
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8083/eureka/
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://admin-monitor:8082
    networks:
      - algorithm-compare-network

  eureka:
    container_name: eureka
    build:
      context: ../AlgorithmCompareBE/Eureka
      dockerfile: eureka.dockerfile
    ports:
      - '8083:8083'
    depends_on:
      - admin-monitor
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8083/eureka/
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://admin-monitor:8082
    networks:
      - algorithm-compare-network

  algorithm-compare-fe:
    container_name: algorithm-compare-fe
    build:
      context: ../AlgorithmCompareFE
      dockerfile: algorithm-compare-fe.dockerfile
    ports:
      - '4200:4200'
    depends_on:
      - algorithm-compare-be
    networks:
      - algorithm-compare-network

  mongodb:
    container_name: algorithm-compare-mongodb
    image: mongo:6.0.8
    ports:
      - "27017:27017"
    networks:
      - algorithm-compare-network

  redis:
    container_name: algorithm-compare-redis
    image: redis:7.0.8
    ports:
      - "6379:6379"
    networks:
      - algorithm-compare-network

  redis-commander:
    container_name: algorithm-compare-redis-commander
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - algorithm-compare-network